# Generated by Django 4.2.20 on 2025-03-23 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(help_text='e.g., Nambale Beans', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('produce_type', models.CharField(choices=[('beans', 'Beans'), ('maize', 'Grain Maize'), ('cowpeas', 'Cowpeas'), ('gnuts', 'G-nuts'), ('rice', 'Rice'), ('soybeans', 'Soybeans')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tonnage_kg', models.PositiveIntegerField(help_text='Minimum 1000kg (1 ton)', validators=[django.core.validators.MinValueValidator(1000)])),
                ('cost_ugx', models.PositiveIntegerField(help_text='Cost in UgX (minimum 5 digits)', validators=[django.core.validators.MinValueValidator(10000)])),
                ('dealer_name', models.CharField(help_text='Full name of the produce supplier', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('branch_name', models.CharField(choices=[('Branch A', 'Branch A'), ('Branch B', 'Branch B')], max_length=50)),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ugandan phone number (e.g., 07XXXXXXXX or 2567XXXXXXXX)', regex='^(07\\d{8}|2567\\d{8})$')])),
                ('selling_price_ugx', models.PositiveIntegerField(help_text='Selling price per kg or bag', validators=[django.core.validators.MinValueValidator(1000)])),
                ('source', models.CharField(choices=[('Dealer', 'Individual Dealer'), ('Company', 'Company'), ('Maganjo Farm', 'Maganjo Farm'), ('Matugga Farm', 'Matugga Farm')], default='Dealer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
