# Generated by Django 4.2.20 on 2025-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='branch_name',
            field=models.CharField(choices=[('Matugga', 'Matugga'), ('Maganjo', 'Maganjo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='cost_ugx',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='dealer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='produce_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='selling_price_ugx',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='tonnage_kg',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
