# Generated by Django 5.2 on 2025-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("branch_name", models.CharField(max_length=50)),
            ],
        ),
    ]
