# Generated by Django 5.2 on 2025-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0002_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="amount_due",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Cash"), ("credit", "Credit")],
                default="cash",
                max_length=10,
            ),
        ),
    ]
