# Generated by Django 4.2.20 on 2025-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0002_alter_procurement_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100)),
                ('tonnage_kg', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('sales_agent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
