# Generated by Django 4.2.20 on 2025-03-25 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('amount_due', models.PositiveIntegerField()),
                ('sales_agent', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('produce_name', models.CharField(max_length=100)),
                ('produce_type', models.CharField(max_length=100)),
                ('tonnage', models.PositiveIntegerField()),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
