# Generated by Django 5.2 on 2025-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0003_sale_amount_due_sale_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlist",
            name="tonnage_kg",
            field=models.PositiveIntegerField(),
        ),
    ]
