# Generated by Django 5.2 on 2025-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0004_alter_creditlist_tonnage_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditsale",
            name="tonnage_kg",
            field=models.PositiveIntegerField(),
        ),
    ]
