# Generated by Django 4.2.20 on 2025-03-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0004_creditsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100)),
                ('produce_type', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('tonnage_available', models.FloatField()),
            ],
        ),
    ]
