# Generated by Django 4.2.20 on 2025-03-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0005_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100)),
                ('tonnage_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buyer_name', models.CharField(max_length=100)),
                ('sales_agent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
