# Generated by Django 5.2 on 2025-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0005_alter_creditsale_tonnage_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditsale",
            name="cleared",
            field=models.BooleanField(default=False),
        ),
    ]
