# Generated by Django 4.2.20 on 2025-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0006_creditsale_cleared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
    ]
