# Generated by Django 4.2.20 on 2025-03-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0011_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
