# Generated by Django 4.2.20 on 2025-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0015_salesagent_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch_name',
            field=models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], default='Matugga', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.TimeField(),
        ),
    ]
