# Generated by Django 4.2.20 on 2025-04-11 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0016_sale_branch_name_alter_sale_date_alter_sale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
