# Generated by Django 4.2.20 on 2025-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0017_alter_sale_date_alter_sale_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditsale',
            name='tonnage',
        ),
        migrations.AddField(
            model_name='creditsale',
            name='branch_name',
            field=models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], default='Maganjo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsale',
            name='tonnage_kg',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
