# Generated by Django 4.2.20 on 2025-04-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0018_remove_creditsale_tonnage_creditsale_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='tonnage_kg',
            field=models.CharField(max_length=225),
        ),
    ]
