# Generated by Django 4.2.20 on 2025-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0019_alter_creditsale_tonnage_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlist',
            name='branch_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
