# Generated by Django 4.2.20 on 2025-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0020_creditlist_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlist',
            name='tonnage',
        ),
        migrations.AddField(
            model_name='creditlist',
            name='tonnage_kg',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
