# Generated by Django 4.2.20 on 2025-04-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kglapp', '0021_remove_creditlist_tonnage_creditlist_tonnage_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Matugga', 'Matugga'), ('Maganjo', 'Maganjo')], max_length=100)),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Manager', 'Manager'), ('Sales Agent', 'Sales Agent')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
