# Generated by Django 4.2.20 on 2025-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0028_alter_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Cereals', 'Cereals'), ('Legumes', 'Legumes'), ('Roots', 'Roots')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
