# Generated by Django 4.2.20 on 2025-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0029_procurement_category_procurement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='tonnage_kg',
            field=models.PositiveIntegerField(),
        ),
    ]
