# Generated by Django 4.2.20 on 2025-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0031_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='faq',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
