# Generated by Django 4.2.20 on 2025-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0032_rename_created_at_faq_submitted_at_faq_is_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
